name: build, test and release main branch

on:
  workflow_dispatch:

#on:
#  push:
#    branches: [ "main" ]
#    paths: 
#      - lucide
#      - src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Checkout lucide
      working-directory: lucide
      run: |
        git submodule update --init --recursive --remote
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore
    - name: Build
      working-directory: src
      run: dotnet build --no-restore
    - name: Test
      working-directory: src
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      working-directory: src
      run: |
        export VERSION="$RELEASE_VERSION_MAJOR.$RELEASE_VERSION_MINOR.$RELEASE_VERSION_PATCH"
        dotnet pack --no-build Lucide.Blazor/Lucide.Blazor.csproj --configuration Release --output $PWD/dist /p:Version=$VERSION
