#on:
#  schedule:
#  - cron: "0 0 * * *"

on:
  workflow_dispatch:
 
jobs:
  update-lucide:
    name: update lucide submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Execute update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /scripts
          chmod +x update-lucide.sh
          ./update-lucide.sh
        
