#on:
#  schedule:
#  - cron: "0 0 * * *"

on:
  workflow_dispatch:
 
jobs:
  update-lucide:
    name: update lucide submodule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        id: checkout-script
        uses: actions/checkout@v3
        
      - name: Execute update script
        id: update-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $PWD/scripts
          chmod +x update-lucide.sh
          ./update-lucide.sh
          
      - name: Create pull request from branch
        id: pull-request-script
        uses: actions/github-script@v6
        env:
          BRANCH: ${{ steps.update-script.outputs.* }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          script: |
            console.log($BRANCH)
            
            const title = "lucide-update";
            const body = "lucide-update";
            const head = $BRANCH; // branch name from last step
            const base = "main";
            
            const { data: pr } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              head,
              base
            });
            
            console.log(`Created PR: ${pr.html_url}`);
            
        
        
