#on:
#  schedule:
#  - cron: "0 0 * * *"

on:
  workflow_dispatch:
 
jobs:
  update-lucide:
    name: update lucide submodule
    permissions:
     contents: write
     pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        id: checkout_script
        uses: actions/checkout@v3
        
      - name: Execute update script
        id: update_script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $PWD/scripts
          chmod +x update-lucide.sh
          ./update-lucide.sh
          
      - name: Create pull request from branch
        id: pull_request_script
        uses: actions/github-script@v6
        env:
          BRANCH: ${{ steps.update_script.outputs.BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          script: |
            const {BRANCH} = process.env;
            const title = "lucide-update";
            const body = "lucide-update";
            const head = BRANCH;
            const base = "main";
            
            const result = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              head,
              base
            });
            
            console.log(`Created PR: ${result.html_url}`);
            
        
        
