name: release

on:
  pull_request:
    types: [closed]
    branches:
      - main
      
jobs:
  create_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request_merged == true
    steps:
     - name: checkout source
       uses: actions/checkout@v3
     - name: create release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: v${{ github.event.pull_request.number }}
         release_name: Release v${{ github.event.pull_request.number }}
         body: "Automated release for lucide-blazor"
         draft: false
         prerelease: false
